title: jck.earth
description: Blog of Justin Craig-Kuhn
baseurl: ''
url: https://jck.earth
github_username: jcraigk
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-feed
include: ['_pages']
collections:
  projects:
    output: true
assets:
  main:
    sources:
      - assets/css/main.scss

########################
# Minimal Mistakes theme
minimal_mistakes_skin: default
logo: /assets/images/logo-earth-128.png
author:
  avatar: /assets/images/jck-avatar-125.png
  bio: Blog of Justin Craig-Kuhn
  location: California, USA
  links: &links
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/jcraigk
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/jcraigk/
footer:
  links: *links

defaults:
  # Global
  - scope:
      path: ''
    values:
      layout: single
      author_profile: true
  # Pages
  - scope:
      path: _pages
    values:
      permalink: /:basename:output_ext
      layout: single
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
      related: true
  # Projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      share: true
search: true
lunr:
  search_within_pages: true
og_image: /assets/images/logo-earth-128.png
